### ISSUE TITLE
Error while installing dependencies 

### ISSUE THREAD

**Issue by abhiram1504** [balajisrinivas/Face-Mask-Detection#6]
ERROR: Could not find a version that satisfies the requirement tensorflow>=1.15.2 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.15.2 (from -r requirements.txt (line 1))
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\abhiram nellutla\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

**Comment by Apzar** [comment]
use python 3.8 version

**Comment by Apzar** [comment]
> ERROR: Could not find a version that satisfies the requirement tensorflow>=1.15.2 (from -r requirements.txt (line 1)) (from versions: none)
> ERROR: No matching distribution found for tensorflow>=1.15.2 (from -r requirements.txt (line 1))
> WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
> You should consider upgrading via the 'c:\users\abhiram nellutla\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

use python 3.8 version

**Comment by Ritvik-Sapra** [comment]
I had a similar problem on windows. Turns out this is a bug in the windows update. Weeks later, when now I have completely given up windows and running Pop!_OS only on my laptop, I run the command `pip3 install -r requirements.txt` and it worked fine. So its a windows update problem. You can't really do anything in it, or there are multiple instances of tensorflow and other libraries lying around in your base (If you're using anaconda, else its called parent directory) and they're interfering with the installation.

**Comment by 4dinkar** [comment]
Hello All,

Please find the error below.

C:\Users\madhubala\detection>pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow>=1.15.2 (from versions: 2.5.0rc0, 2.5.0rc1, 2.
5.0rc2)
ERROR: No matching distribution found for tensorflow>=1.15.2

C:\Users\madhubala\detection>

**Comment by Dark-Programm** [comment]
Use python3-pip to install the required dependencies.

That worked for me.

**Comment by MrinalRaut** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Python\Face_mask_detection_master\Face-Mask-Detection-master\detect_mask_video.py", line 5, in <module>
    from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
  File "C:\Users\User\Python\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\User\Python\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\User\Python\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\User\Python\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()
  File "C:\Users\User\Python\lib\site-packages\tensorflow\python\platform\self_check.py", line 54, in preload_check
    raise ImportError(
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

This is the error I'm facing. 
please suggest me a solution on rautmrinal@gmail.com
